# Generated by Django 4.1.3 on 2022-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(blank=True, max_length=210, null=True)),
                ('brand', models.CharField(blank=True, max_length=210, null=True)),
                ('provider', models.CharField(blank=True, max_length=210, null=True)),
                ('country_of_Origin', models.CharField(blank=True, max_length=210, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=210, null=True)),
                ('creater', models.CharField(blank=True, max_length=210, null=True)),
                ('email', models.CharField(blank=True, max_length=210, null=True)),
                ('information_of_company', models.CharField(blank=True, max_length=210, null=True)),
            ],
        ),
    ]
